inherit_gem:
  google-style: google-style.yml

AllCops:
  Exclude:
    - "integration/**/*"
    - "spec/**/*"
    - "test/**/*"
Metrics/ClassLength:
  Max: 200
Metrics/ModuleLength:
  Max: 110
Metrics/BlockLength:
  Exclude:
    - "googleauth.gemspec"
