inherit_gem:
  google-style: google-style.yml

AllCops:
  Exclude:
    - "integration/**/*"
    - "spec/**/*"
    - "test/**/*"
Metrics/BlockLength:
  Exclude:
    - "googleauth.gemspec"
Metrics/ClassLength:
  Max: 200
Metrics/CyclomaticComplexity:
  Max: 15
Metrics/ModuleLength:
  Max: 200
Metrics/PerceivedComplexity:
  Max: 15
