name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  CI:
    if: ${{ github.repository == 'googleapis/google-auth-library-ruby' }}
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            ruby: "2.7"
            task: test , spec
          - os: ubuntu-20.04
            ruby: "3.0"
            task: test , spec
          - os: ubuntu-20.04
            ruby: "3.1"
            task: test , spec  
          - os: ubuntu-22.04
            ruby: "3.2"
            task: test , spec
          - os: macos-latest
            ruby: "3.2"
            task: test , spec
          - os: windows-latest
            ruby: "3.2"
            task: test , spec
          - os: ubuntu-latest
            ruby: "3.2"
            task: rubocop , integration , build , yardoc , linkinator
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Install Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "${{ matrix.ruby }}"
    - name: Install NodeJS 16.x
      uses: actions/setup-node@v4
      with:
        node-version: "16.x"
    - name: Install dependencies
      shell: bash
      run: "gem install --no-document bundler toys && bundle install"
    - name: Test ${{ matrix.task }}
      shell: bash
      run: toys do ${{ matrix.task }} < /dev/null
