name: CI

permissions:
  contents: read
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  CI:
    if: ${{ github.repository == 'googleapis/google-auth-library-ruby' }}
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            ruby: "3.2"
            task: test , spec
          - os: ubuntu-latest
            ruby: "3.3"
            task: test , spec
          - os: ubuntu-latest
            ruby: "3.4"
            task: test , spec
          - os: ubuntu-latest
            ruby: "4.0"
            task: test , spec
          - os: macos-latest
            ruby: "4.0"
            task: test , spec
          - os: windows-latest
            ruby: "4.0"
            task: test , spec
          - os: ubuntu-latest
            ruby: "4.0"
            task: rubocop , integration , build , yardoc , linkinator
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repo
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      with:
        persist-credentials: false
    - name: Install Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@9eb537ca036ebaed86729dcb9309076e4c5c3b74 # v1
      with:
        ruby-version: "${{ matrix.ruby }}"
    - name: Install NodeJS 18.x
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      with:
        node-version: "18.x"
    - name: Install dependencies
      shell: bash
      run: |
        gem install --no-document toys
        bundle install
    - name: Test ${{ matrix.task }}
      shell: bash
      run: |
        for task in $(echo "${{ matrix.task }}" | tr ',' ' '); do
          toys "$task" < /dev/null
        done
