name: Rake CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Rake-CI:
    strategy:
      matrix:
        os: [ubuntu-latest]
        ruby: ["3.4"]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Install Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "${{ matrix.ruby }}"
        bundler-cache: true
    - name: Install NodeJS 18.x
      uses: actions/setup-node@v4
      with:
        node-version: "18.x"
    - name: Run all Rake tasks
      shell: bash
      run: bundle exec rake ci
